# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 598036c58dc84cf69cbc46c80000e5f4427aefd7625ea49797b2c774c296594a4337f23f111d45e70b92cb8bdeae2866232e0370301cdba5611ab4c3f3e4259c

test:
  secret_key_base: 498f2436508e06b19e5fb70bd24c311783aa6cbcf5168bc0c7a944cb43906e405ae8286c54278ec40f2ea980dc99400330c7b7b912573de87ce9e9990a22c04f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
